/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Corp Access
         * @description All registered corps with their accounting-access status (cross-tenant).
         */
        get: operations["list_corp_access_api_v1_admin_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/access/{corporation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Grant Corp Access
         * @description Grant or extend a corp's access (`source=admin`); null expiry = perpetual.
         */
        put: operations["grant_corp_access_api_v1_admin_access__corporation_id__put"];
        post?: never;
        /**
         * Revoke Corp Access
         * @description Revoke a corp's access. Idempotent.
         */
        delete: operations["revoke_corp_access_api_v1_admin_access__corporation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Payments
         * @description Recent incoming payments (newest first); `?unmatched=true` filters to the ones
         *     awaiting a manual match.
         */
        get: operations["list_payments_api_v1_admin_payments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payments/{payment_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Payment
         * @description Apply an unmatched payment to a corp (extends their access by the periods the
         *     amount covers).
         */
        post: operations["match_payment_api_v1_admin_payments__payment_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wallet Status */
        get: operations["get_wallet_status_api_v1_admin_wallet_get"];
        put?: never;
        post?: never;
        /** Revoke Wallet */
        delete: operations["revoke_wallet_api_v1_admin_wallet_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wallet/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorize Wallet
         * @description Begin the operator wallet grant: mint state + PKCE, return the SSO URL.
         */
        post: operations["authorize_wallet_api_v1_admin_wallet_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wallet/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Wallet
         * @description Complete the grant: validate state, exchange the code, store the token.
         */
        post: operations["complete_wallet_api_v1_admin_wallet_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appraisals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appraisals */
        get: operations["list_appraisals_api_v1_appraisals_get"];
        put?: never;
        /** Create Appraisal */
        post: operations["create_appraisal_api_v1_appraisals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appraisals/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appraisal */
        get: operations["get_appraisal_api_v1_appraisals__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appraisals/{public_id}/open-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Contract
         * @description Open the appraisal's matched contract in the caller's own EVE client (ADR-0038),
         *     using the login refresh token held encrypted in their session.
         */
        post: operations["open_contract_api_v1_appraisals__public_id__open_contract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin Login
         * @description Begin login: mint state + PKCE (stashed in the session) and return the EVE
         *     authorization URL for the SPA to redirect to.
         */
        post: operations["begin_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Complete login: validate the OAuth state, exchange the code, open a session.
         */
        post: operations["create_session_api_v1_auth_session_post"];
        /**
         * Delete Session
         * @description Log out: clear the session cookie.
         */
        delete: operations["delete_session_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Corporation */
        post: operations["register_corporation_api_v1_corporations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Corporation */
        get: operations["get_my_corporation_api_v1_corporations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/accounting-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Accounting Access */
        get: operations["get_accounting_access_api_v1_corporations_me_accounting_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_corporations_me_config_get"];
        /** Update Config */
        put: operations["update_config_api_v1_corporations_me_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_corporations_me_locations_get"];
        put?: never;
        /** Add Location */
        post: operations["add_location_api_v1_corporations_me_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Location */
        delete: operations["remove_location_api_v1_corporations_me_locations__location_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managers */
        get: operations["list_managers_api_v1_corporations_me_managers_get"];
        put?: never;
        /** Add Manager */
        post: operations["add_manager_api_v1_corporations_me_managers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/managers/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Manager */
        delete: operations["remove_manager_api_v1_corporations_me_managers__character_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_corporations_me_roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/roster/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Members
         * @description Search the synced roster by name (empty until the corp roster has been synced).
         */
        get: operations["search_members_api_v1_corporations_me_roster_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/roster/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Manually re-pull the roster with the stored token (rate-limited; 429 if too soon).
         */
        post: operations["refresh_api_v1_corporations_me_roster_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_corporations_me_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/rules/{target_kind}/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Rule
         * @description Create or replace the rule for a target (idempotent). 201 on create, 200 on
         *     replace.
         */
        put: operations["set_rule_api_v1_corporations_me_rules__target_kind___target_id__put"];
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_corporations_me_rules__target_kind___target_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/structure-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_corporations_me_structure_token_get"];
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_api_v1_corporations_me_structure_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/structure-token/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorize
         * @description Begin the corp ESI access grant: mint state + PKCE and return the SSO URL.
         */
        post: operations["authorize_api_v1_corporations_me_structure_token_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/structure-token/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search the corp's accessible structures by name (requires prior authorization).
         */
        get: operations["search_api_v1_corporations_me_structure_token_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/structure-token/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete
         * @description Complete the grant: validate state, exchange the code, store the token, and
         *     best-effort populate the roster (works if the connected character can read it).
         */
        post: operations["complete_api_v1_corporations_me_structure_token_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB connectivity check (proves the two halves talk).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Market Groups */
        get: operations["list_market_groups_api_v1_market_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stations
         * @description Search seeded NPC stations by system or station name, for the hub picker.
         */
        get: operations["search_stations_api_v1_stations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/types/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Types */
        get: operations["search_types_api_v1_types_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description The app version (bumped per merged PR). Public — shown in the UI footer.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessGrantRequest
         * @description Grant/extend a corp's access. Omitted/null `expires_at` = perpetual.
         */
        AccessGrantRequest: {
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * AccountingAccessOut
         * @description A corp's accounting-access status plus how to pay (manager-visible). When no
         *     operator wallet is connected (`payment_configured` False), the UI shows status
         *     only — there is nowhere to send ISK yet.
         */
        AccountingAccessOut: {
            /** Active */
            active: boolean;
            /** Expires At */
            expires_at?: string | null;
            /** Operator Character Name */
            operator_character_name?: string | null;
            /** Payment Configured */
            payment_configured: boolean;
            /** Period Days */
            period_days: number;
            /** Price Isk */
            price_isk: number;
            /** Reference */
            reference: string;
        };
        /**
         * AppraisalCreateRequest
         * @description Items may be supplied structured, as a raw EVE paste, or both — but at least
         *     one must be non-empty. The paste is parsed and name-resolved server-side. The
         *     combined item count (structured + paste) is capped in the use case; the bounds
         *     here are the cheap first line of defense (ADR-0014, EVE's 1000-item contract).
         */
        AppraisalCreateRequest: {
            /** Delivery Location Id */
            delivery_location_id?: string | null;
            /** Items */
            items?: components["schemas"]["AppraisalItemIn"][];
            /** Paste */
            paste?: string | null;
        };
        /** AppraisalItemIn */
        AppraisalItemIn: {
            /** Quantity */
            quantity: number;
            /** Type Id */
            type_id: number;
        };
        /** AppraisalLineOut */
        AppraisalLineOut: {
            /** Basis */
            basis: ("buy" | "sell" | "split") | null;
            /** Line Total */
            line_total: string;
            /** Market Hub Id */
            market_hub_id?: string | null;
            /** Market Hub Name */
            market_hub_name?: string | null;
            /** Percentage */
            percentage: string | null;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string | null;
            reprocess?: components["schemas"]["ReprocessBreakdownOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected";
            /** Type Id */
            type_id: number | null;
            /** Type Name */
            type_name: string;
            /** Unit Price */
            unit_price: string | null;
            /** Unit Value */
            unit_value: string | null;
        };
        /** AppraisalOut */
        AppraisalOut: {
            /** Accepted Total */
            accepted_total: string;
            /** Contract Status */
            contract_status?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Character Id */
            created_by_character_id: number;
            /** Created By Character Name */
            created_by_character_name?: string | null;
            /** Delivery Location Id */
            delivery_location_id?: string | null;
            /** Delivery Location Name */
            delivery_location_name?: string | null;
            /** Lines */
            lines: components["schemas"]["AppraisalLineOut"][];
            /** Market Hub Id */
            market_hub_id: string;
            /** Public Id */
            public_id: string;
            /** Rejected Count */
            rejected_count: number;
        };
        /** AppraisalSummaryOut */
        AppraisalSummaryOut: {
            /** Accepted Total */
            accepted_total: string;
            /** Contract Status */
            contract_status?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Character Id */
            created_by_character_id: number;
            /** Created By Character Name */
            created_by_character_name?: string | null;
            /** Delivery Location Id */
            delivery_location_id?: string | null;
            /** Delivery Location Name */
            delivery_location_name?: string | null;
            /** Market Hub Id */
            market_hub_id: string;
            /** Public Id */
            public_id: string;
            /** Rejected Count */
            rejected_count: number;
        };
        /** ConfigOut */
        ConfigOut: {
            /**
             * Aggregate Field
             * @enum {string}
             */
            aggregate_field: "weighted_average" | "max" | "min" | "median" | "percentile";
            /** Corporation Id */
            corporation_id: number;
            /**
             * Default Accepted
             * @default true
             */
            default_accepted: boolean;
            /**
             * Default Basis
             * @enum {string}
             */
            default_basis: "buy" | "sell" | "split";
            /** Default Percentage */
            default_percentage: string;
            /** Market Hub Id */
            market_hub_id: string;
            /**
             * Market Hub Kind
             * @default npc_station
             * @enum {string}
             */
            market_hub_kind: "npc_station" | "structure";
            /** Market Hub Name */
            market_hub_name?: string | null;
            /** Market Region Id */
            market_region_id?: number | null;
        };
        /** ConfigUpdateRequest */
        ConfigUpdateRequest: {
            /**
             * Aggregate Field
             * @enum {string}
             */
            aggregate_field: "weighted_average" | "max" | "min" | "median" | "percentile";
            /**
             * Default Accepted
             * @default true
             */
            default_accepted: boolean;
            /**
             * Default Basis
             * @enum {string}
             */
            default_basis: "buy" | "sell" | "split";
            /** Default Percentage */
            default_percentage: number | string;
            /** Market Hub Id */
            market_hub_id: string;
            /**
             * Market Hub Kind
             * @default npc_station
             * @enum {string}
             */
            market_hub_kind: "npc_station" | "structure";
            /** Market Hub Name */
            market_hub_name?: string | null;
        };
        /**
         * CorpAccessOut
         * @description One corp's access to the accounting add-on, as shown on the admin page.
         */
        CorpAccessOut: {
            /** Active */
            active: boolean;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /** Expires At */
            expires_at?: string | null;
            /** Granted At */
            granted_at?: string | null;
            /** Granted By Character Id */
            granted_by_character_id?: number | null;
            /** Source */
            source?: ("payment" | "admin") | null;
        };
        /**
         * CorpMemberOut
         * @description A corp member matched by the manager-designation search.
         */
        CorpMemberOut: {
            /** Character Id */
            character_id: number;
            /** Name */
            name: string;
        };
        /** CorporationOut */
        CorporationOut: {
            /** Ceo Character Id */
            ceo_character_id: number;
            /** Corporation Id */
            corporation_id: number;
            /** Name */
            name: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Registered By Character Id */
            registered_by_character_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocationCreateRequest
         * @description Add a drop-off location. For an NPC station the name is resolved server-side
         *     from the SDE (any supplied name is ignored); for a structure — which has no SDE —
         *     the name from the structure search is required.
         */
        LocationCreateRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "npc_station" | "structure";
            /** Location Id */
            location_id: string;
            /** Name */
            name?: string | null;
        };
        /**
         * LocationOut
         * @description An accepted buyback drop-off location (ADR-0030).
         */
        LocationOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "npc_station" | "structure";
            /** Location Id */
            location_id: string;
            /** Name */
            name: string;
            /** System Name */
            system_name?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** LoginUrlResponse */
        LoginUrlResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** State */
            state: string;
        };
        /** ManagerCreateRequest */
        ManagerCreateRequest: {
            /** Character Id */
            character_id: number;
        };
        /** ManagerOut */
        ManagerOut: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Granted By Character Id */
            granted_by_character_id: number;
        };
        /** MarketGroupOut */
        MarketGroupOut: {
            /** Market Group Id */
            market_group_id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * OperatorWalletStatus
         * @description The operator wallet connection (ADR-0042), as shown on the admin page.
         */
        OperatorWalletStatus: {
            /** Character Name */
            character_name?: string | null;
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Created At */
            created_at?: string | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
        };
        /**
         * PaymentMatchRequest
         * @description Apply an unmatched payment to a corporation (by EVE corp id).
         */
        PaymentMatchRequest: {
            /** Corporation Id */
            corporation_id: number;
        };
        /**
         * PaymentOut
         * @description One incoming ISK transfer seen in the operator's wallet (ADR-0042).
         */
        PaymentOut: {
            /** Amount */
            amount: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched */
            matched: boolean;
            /** Matched Corporation Name */
            matched_corporation_name?: string | null;
            /**
             * Periods Granted
             * @default 0
             */
            periods_granted: number;
            /** Reason */
            reason?: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Sender Name */
            sender_name?: string | null;
        };
        /**
         * ReprocessBreakdownOut
         * @description How a reprocess-priced ore line breaks down (ADR-0026): the minerals it yields
         *     plus any sub-batch leftover priced at the ore's own market price.
         */
        ReprocessBreakdownOut: {
            /** Leftover Units */
            leftover_units: number;
            /** Leftover Value */
            leftover_value: string;
            /** Minerals */
            minerals: components["schemas"]["ReprocessMineralOut"][];
        };
        /** ReprocessMineralOut */
        ReprocessMineralOut: {
            /** Quantity */
            quantity: string;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name: string;
            /** Unit Value */
            unit_value: string | null;
            /** Value */
            value: string;
        };
        /**
         * RosterStatusOut
         * @description The corp roster's sync state, shown on the Config panel + Managers page.
         */
        RosterStatusOut: {
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /** Synced */
            synced: boolean;
            /** Synced At */
            synced_at?: string | null;
        };
        /** RuleOut */
        RuleOut: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Basis */
            basis: ("buy" | "sell" | "split") | null;
            /**
             * Compressed Only
             * @default false
             */
            compressed_only: boolean;
            /** Enabled */
            enabled: boolean;
            /** Folder */
            folder?: string | null;
            /** Market Hub Id */
            market_hub_id?: string | null;
            /** Market Hub Kind */
            market_hub_kind?: ("npc_station" | "structure") | null;
            /** Market Hub Name */
            market_hub_name?: string | null;
            /** Percentage */
            percentage: string;
            /**
             * Reprocess
             * @default false
             */
            reprocess: boolean;
            /** Target Id */
            target_id: number;
            /**
             * Target Kind
             * @enum {string}
             */
            target_kind: "market_group" | "type";
            /** Target Market Group Id */
            target_market_group_id?: number | null;
            /** Target Name */
            target_name?: string | null;
        };
        /**
         * RulePutRequest
         * @description The full rule state for a target (the target comes from the URL). `PUT` is an
         *     idempotent create-or-replace, so this is the complete representation — omitting
         *     the hub fields clears any hub override (ADR-0031).
         */
        RulePutRequest: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Basis */
            basis?: ("buy" | "sell" | "split") | null;
            /**
             * Compressed Only
             * @default false
             */
            compressed_only: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Folder */
            folder?: string | null;
            /** Market Hub Id */
            market_hub_id?: string | null;
            /** Market Hub Kind */
            market_hub_kind?: ("npc_station" | "structure") | null;
            /** Market Hub Name */
            market_hub_name?: string | null;
            /** Percentage */
            percentage: number | string;
            /**
             * Reprocess
             * @default false
             */
            reprocess: boolean;
        };
        /**
         * SessionUser
         * @description The authenticated user returned by /me and /login (API DTO).
         */
        SessionUser: {
            /**
             * Can Open Contract
             * @default false
             */
            can_open_contract: boolean;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /**
             * Corporation Registered
             * @default false
             */
            corporation_registered: boolean;
            /**
             * Is App Admin
             * @default false
             */
            is_app_admin: boolean;
            /**
             * Is Director
             * @default false
             */
            is_director: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "manager" | "ceo";
        };
        /** StationSearchResult */
        StationSearchResult: {
            /** Name */
            name: string;
            /** Region Id */
            region_id: number;
            /** Station Id */
            station_id: number;
            /** System Name */
            system_name: string;
        };
        /**
         * StructureAuthorizeRequest
         * @description The OAuth callback payload completing the structure-access grant.
         */
        StructureAuthorizeRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /**
         * StructureAuthorizeResponse
         * @description The SSO URL the SPA redirects to, to grant structure-market access.
         */
        StructureAuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** State */
            state: string;
        };
        /**
         * StructureSearchResult
         * @description A structure the authorizing character can access, matched by name.
         */
        StructureSearchResult: {
            /** Name */
            name: string;
            /** Structure Id */
            structure_id: string;
        };
        /**
         * StructureTokenStatus
         * @description The corp's structure-market authorization status (never the token itself).
         */
        StructureTokenStatus: {
            /** Authorized */
            authorized: boolean;
            /** Character Name */
            character_name?: string | null;
            /**
             * Configured
             * @default true
             */
            configured: boolean;
            /** Created At */
            created_at?: string | null;
            /**
             * Expired
             * @default false
             */
            expired: boolean;
            /** Failed Since */
            failed_since?: string | null;
            /** Replaced Character Name */
            replaced_character_name?: string | null;
            /** Scopes */
            scopes?: string | null;
        };
        /** TypeSearchResult */
        TypeSearchResult: {
            /** Market Group Id */
            market_group_id: number | null;
            /** Name */
            name: string;
            /** Type Id */
            type_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalletAuthorizeRequest */
        WalletAuthorizeRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** WalletAuthorizeResponse */
        WalletAuthorizeResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** State */
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_corp_access_api_v1_admin_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpAccessOut"][];
                };
            };
        };
    };
    grant_corp_access_api_v1_admin_access__corporation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpAccessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_corp_access_api_v1_admin_access__corporation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corporation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_api_v1_admin_payments_get: {
        parameters: {
            query?: {
                unmatched?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_payment_api_v1_admin_payments__payment_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_status_api_v1_admin_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorWalletStatus"];
                };
            };
        };
    };
    revoke_wallet_api_v1_admin_wallet_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorize_wallet_api_v1_admin_wallet_authorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletAuthorizeResponse"];
                };
            };
        };
    };
    complete_wallet_api_v1_admin_wallet_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletAuthorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorWalletStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appraisals_api_v1_appraisals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalSummaryOut"][];
                };
            };
        };
    };
    create_appraisal_api_v1_appraisals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppraisalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appraisal_api_v1_appraisals__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_contract_api_v1_appraisals__public_id__open_contract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginUrlResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    create_session_api_v1_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_corporation_api_v1_corporations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationOut"];
                };
            };
        };
    };
    get_my_corporation_api_v1_corporations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationOut"];
                };
            };
        };
    };
    get_accounting_access_api_v1_corporations_me_accounting_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountingAccessOut"];
                };
            };
        };
    };
    get_config_api_v1_corporations_me_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    update_config_api_v1_corporations_me_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_v1_corporations_me_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
        };
    };
    add_location_api_v1_corporations_me_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_location_api_v1_corporations_me_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_managers_api_v1_corporations_me_managers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerOut"][];
                };
            };
        };
    };
    add_manager_api_v1_corporations_me_managers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_manager_api_v1_corporations_me_managers__character_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_corporations_me_roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterStatusOut"];
                };
            };
        };
    };
    search_members_api_v1_corporations_me_roster_members_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_corporations_me_roster_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterStatusOut"];
                };
            };
        };
    };
    list_rules_api_v1_corporations_me_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    set_rule_api_v1_corporations_me_rules__target_kind___target_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_kind: "market_group" | "type";
                target_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_corporations_me_rules__target_kind___target_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_kind: "market_group" | "type";
                target_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_corporations_me_structure_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureTokenStatus"];
                };
            };
        };
    };
    revoke_api_v1_corporations_me_structure_token_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authorize_api_v1_corporations_me_structure_token_authorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureAuthorizeResponse"];
                };
            };
        };
    };
    search_api_v1_corporations_me_structure_token_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_api_v1_corporations_me_structure_token_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructureAuthorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureTokenStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_market_groups_api_v1_market_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketGroupOut"][];
                };
            };
        };
    };
    search_stations_api_v1_stations_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_types_api_v1_types_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
