/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/appraisals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appraisals */
        get: operations["list_appraisals_api_v1_appraisals_get"];
        put?: never;
        /** Create Appraisal */
        post: operations["create_appraisal_api_v1_appraisals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appraisals/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appraisal */
        get: operations["get_appraisal_api_v1_appraisals__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin Login
         * @description Begin login: mint state + PKCE (stashed in the session) and return the EVE
         *     authorization URL for the SPA to redirect to.
         */
        post: operations["begin_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Complete login: validate the OAuth state, exchange the code, open a session.
         */
        post: operations["create_session_api_v1_auth_session_post"];
        /**
         * Delete Session
         * @description Log out: clear the session cookie.
         */
        delete: operations["delete_session_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Corporation */
        post: operations["register_corporation_api_v1_corporations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Corporation */
        get: operations["get_my_corporation_api_v1_corporations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_corporations_me_config_get"];
        /** Update Config */
        put: operations["update_config_api_v1_corporations_me_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managers */
        get: operations["list_managers_api_v1_corporations_me_managers_get"];
        put?: never;
        /** Add Manager */
        post: operations["add_manager_api_v1_corporations_me_managers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/managers/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Manager */
        delete: operations["remove_manager_api_v1_corporations_me_managers__character_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_corporations_me_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corporations/me/rules/{target_kind}/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Rule
         * @description Create or replace the rule for a target (idempotent). 201 on create, 200 on
         *     replace.
         */
        put: operations["set_rule_api_v1_corporations_me_rules__target_kind___target_id__put"];
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_corporations_me_rules__target_kind___target_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB connectivity check (proves the two halves talk).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Market Groups */
        get: operations["list_market_groups_api_v1_market_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/types/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Types */
        get: operations["search_types_api_v1_types_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description The app version (bumped per merged PR). Public — shown in the UI footer.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppraisalCreateRequest
         * @description Items may be supplied structured, as a raw EVE paste, or both — but at least
         *     one must be non-empty. The paste is parsed and name-resolved server-side. The
         *     combined item count (structured + paste) is capped in the use case; the bounds
         *     here are the cheap first line of defense (ADR-0014, EVE's 1000-item contract).
         */
        AppraisalCreateRequest: {
            /** Items */
            items?: components["schemas"]["AppraisalItemIn"][];
            /** Paste */
            paste?: string | null;
        };
        /** AppraisalItemIn */
        AppraisalItemIn: {
            /** Quantity */
            quantity: number;
            /** Type Id */
            type_id: number;
        };
        /** AppraisalLineOut */
        AppraisalLineOut: {
            /** Basis */
            basis: ("buy" | "sell" | "split") | null;
            /** Line Total */
            line_total: string;
            /** Percentage */
            percentage: string | null;
            /** Quantity */
            quantity: number;
            /** Reason */
            reason: string | null;
            reprocess?: components["schemas"]["ReprocessBreakdownOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected";
            /** Type Id */
            type_id: number | null;
            /** Type Name */
            type_name: string;
            /** Unit Price */
            unit_price: string | null;
            /** Unit Value */
            unit_value: string | null;
        };
        /** AppraisalOut */
        AppraisalOut: {
            /** Accepted Total */
            accepted_total: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Character Id */
            created_by_character_id: number;
            /** Created By Character Name */
            created_by_character_name?: string | null;
            /** Lines */
            lines: components["schemas"]["AppraisalLineOut"][];
            /** Market Hub Id */
            market_hub_id: number;
            /** Public Id */
            public_id: string;
            /** Rejected Count */
            rejected_count: number;
        };
        /** AppraisalSummaryOut */
        AppraisalSummaryOut: {
            /** Accepted Total */
            accepted_total: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Character Id */
            created_by_character_id: number;
            /** Created By Character Name */
            created_by_character_name?: string | null;
            /** Market Hub Id */
            market_hub_id: number;
            /** Public Id */
            public_id: string;
            /** Rejected Count */
            rejected_count: number;
        };
        /** ConfigOut */
        ConfigOut: {
            /**
             * Aggregate Field
             * @enum {string}
             */
            aggregate_field: "weighted_average" | "max" | "min" | "median" | "percentile";
            /** Corporation Id */
            corporation_id: number;
            /**
             * Default Accepted
             * @default true
             */
            default_accepted: boolean;
            /**
             * Default Basis
             * @enum {string}
             */
            default_basis: "buy" | "sell" | "split";
            /** Default Percentage */
            default_percentage: string;
            /** Market Hub Id */
            market_hub_id: number;
            /**
             * Market Hub Kind
             * @default npc_station
             * @enum {string}
             */
            market_hub_kind: "npc_station" | "structure";
            /** Market Hub Name */
            market_hub_name?: string | null;
            /** Market Region Id */
            market_region_id?: number | null;
        };
        /** ConfigUpdateRequest */
        ConfigUpdateRequest: {
            /**
             * Aggregate Field
             * @enum {string}
             */
            aggregate_field: "weighted_average" | "max" | "min" | "median" | "percentile";
            /**
             * Default Accepted
             * @default true
             */
            default_accepted: boolean;
            /**
             * Default Basis
             * @enum {string}
             */
            default_basis: "buy" | "sell" | "split";
            /** Default Percentage */
            default_percentage: number | string;
            /** Market Hub Id */
            market_hub_id: number;
            /**
             * Market Hub Kind
             * @default npc_station
             * @enum {string}
             */
            market_hub_kind: "npc_station" | "structure";
        };
        /** CorporationOut */
        CorporationOut: {
            /** Ceo Character Id */
            ceo_character_id: number;
            /** Corporation Id */
            corporation_id: number;
            /** Name */
            name: string;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Registered By Character Id */
            registered_by_character_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** LoginUrlResponse */
        LoginUrlResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** State */
            state: string;
        };
        /** ManagerCreateRequest */
        ManagerCreateRequest: {
            /** Character Id */
            character_id: number;
        };
        /** ManagerOut */
        ManagerOut: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Granted By Character Id */
            granted_by_character_id: number;
        };
        /** MarketGroupOut */
        MarketGroupOut: {
            /** Market Group Id */
            market_group_id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * ReprocessBreakdownOut
         * @description How a reprocess-priced ore line breaks down (ADR-0026): the minerals it yields
         *     plus any sub-batch leftover priced at the ore's own market price.
         */
        ReprocessBreakdownOut: {
            /** Leftover Units */
            leftover_units: number;
            /** Leftover Value */
            leftover_value: string;
            /** Minerals */
            minerals: components["schemas"]["ReprocessMineralOut"][];
        };
        /** ReprocessMineralOut */
        ReprocessMineralOut: {
            /** Quantity */
            quantity: string;
            /** Type Id */
            type_id: number;
            /** Type Name */
            type_name: string;
            /** Unit Value */
            unit_value: string | null;
            /** Value */
            value: string;
        };
        /** RuleOut */
        RuleOut: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Basis */
            basis: ("buy" | "sell" | "split") | null;
            /**
             * Compressed Only
             * @default false
             */
            compressed_only: boolean;
            /** Enabled */
            enabled: boolean;
            /** Percentage */
            percentage: string;
            /**
             * Reprocess
             * @default false
             */
            reprocess: boolean;
            /** Target Id */
            target_id: number;
            /**
             * Target Kind
             * @enum {string}
             */
            target_kind: "market_group" | "type";
            /** Target Name */
            target_name?: string | null;
        };
        /**
         * RulePutRequest
         * @description The full rule state for a target (the target comes from the URL). `PUT` is an
         *     idempotent create-or-replace, so this is the complete representation.
         */
        RulePutRequest: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Basis */
            basis?: ("buy" | "sell" | "split") | null;
            /**
             * Compressed Only
             * @default false
             */
            compressed_only: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Percentage */
            percentage: number | string;
            /**
             * Reprocess
             * @default false
             */
            reprocess: boolean;
        };
        /**
         * SessionUser
         * @description The authenticated user returned by /me and /login (API DTO).
         */
        SessionUser: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /**
             * Corporation Registered
             * @default false
             */
            corporation_registered: boolean;
            /**
             * Is Director
             * @default false
             */
            is_director: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "manager" | "ceo";
        };
        /** TypeSearchResult */
        TypeSearchResult: {
            /** Market Group Id */
            market_group_id: number | null;
            /** Name */
            name: string;
            /** Type Id */
            type_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_appraisals_api_v1_appraisals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalSummaryOut"][];
                };
            };
        };
    };
    create_appraisal_api_v1_appraisals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppraisalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appraisal_api_v1_appraisals__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppraisalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginUrlResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    create_session_api_v1_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_corporation_api_v1_corporations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationOut"];
                };
            };
        };
    };
    get_my_corporation_api_v1_corporations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporationOut"];
                };
            };
        };
    };
    get_config_api_v1_corporations_me_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    update_config_api_v1_corporations_me_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_managers_api_v1_corporations_me_managers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerOut"][];
                };
            };
        };
    };
    add_manager_api_v1_corporations_me_managers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_manager_api_v1_corporations_me_managers__character_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_corporations_me_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    set_rule_api_v1_corporations_me_rules__target_kind___target_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_kind: "market_group" | "type";
                target_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RulePutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_corporations_me_rules__target_kind___target_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_kind: "market_group" | "type";
                target_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_market_groups_api_v1_market_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketGroupOut"][];
                };
            };
        };
    };
    search_types_api_v1_types_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
