"""pricing rule accepted

Revision ID: 07757f6adc0a
Revises: 52b61153a13d
Create Date: 2026-06-08 00:31:03.943198

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07757f6adc0a'
down_revision: str | None = '52b61153a13d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('accepted', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'accepted')
    # ### end Alembic commands ###
