"""rule hub override and line hub snapshot

Revision ID: 0cb01ad2fb89
Revises: a238fb904f45
Create Date: 2026-06-12 02:42:18.588872

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb01ad2fb89'
down_revision: str | None = 'a238fb904f45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appraisal_lines', sa.Column('market_hub_id', sa.String(), nullable=True))
    op.add_column('appraisal_lines', sa.Column('market_hub_name', sa.String(), nullable=True))
    op.add_column('pricing_rules', sa.Column('market_hub_id', sa.String(), nullable=True))
    op.add_column('pricing_rules', sa.Column('market_hub_kind', sa.Enum('npc_station', 'structure', name='market_hub_kind', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('pricing_rules', sa.Column('market_region_id', sa.Integer(), nullable=True))
    op.add_column('pricing_rules', sa.Column('market_hub_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'market_hub_name')
    op.drop_column('pricing_rules', 'market_region_id')
    op.drop_column('pricing_rules', 'market_hub_kind')
    op.drop_column('pricing_rules', 'market_hub_id')
    op.drop_column('appraisal_lines', 'market_hub_name')
    op.drop_column('appraisal_lines', 'market_hub_id')
    # ### end Alembic commands ###
