"""appraisal line reprocess breakdown

Revision ID: 14d2c0ed584b
Revises: 27a487acc646
Create Date: 2026-06-07 23:40:36.616092

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d2c0ed584b'
down_revision: str | None = '27a487acc646'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appraisal_lines', sa.Column('reprocess', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appraisal_lines', 'reprocess')
    # ### end Alembic commands ###
