"""sde_stations for the hub picker

Revision ID: 1bef3dc47aeb
Revises: b78a43a8d166
Create Date: 2026-06-09 18:26:01.690580

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bef3dc47aeb'
down_revision: str | None = 'b78a43a8d166'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_stations',
    sa.Column('station_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_sde_stations_name'), 'sde_stations', ['name'], unique=False)
    op.create_index(op.f('ix_sde_stations_system_name'), 'sde_stations', ['system_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sde_stations_system_name'), table_name='sde_stations')
    op.drop_index(op.f('ix_sde_stations_name'), table_name='sde_stations')
    op.drop_table('sde_stations')
    # ### end Alembic commands ###
