"""ore reprocess pricing

Revision ID: 27a487acc646
Revises: a6cb1eb62c7c
Create Date: 2026-06-07 23:20:52.459746

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a487acc646'
down_revision: str | None = 'a6cb1eb62c7c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_type_materials',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('material_type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type_id', 'material_type_id')
    )
    op.add_column('pricing_rules', sa.Column('reprocess', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sde_types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('sde_types', sa.Column('portion_size', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sde_types', 'portion_size')
    op.drop_column('sde_types', 'category_id')
    op.drop_column('pricing_rules', 'reprocess')
    op.drop_table('sde_type_materials')
    # ### end Alembic commands ###
