"""Add public_id to pricing_rules

Revision ID: 2ace3fe1aa07
Revises: a668a2fb711c
Create Date: 2026-06-07 11:08:02.425065

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ace3fe1aa07'
down_revision: str | None = 'a668a2fb711c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_pricing_rules_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_rules_public_id'))
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
