"""hangar stock snapshot adr 0050

Revision ID: 4089b6409378
Revises: c4e7f2a9d851
Create Date: 2026-08-11 22:49:27.718100

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4089b6409378'
down_revision: str | None = 'c4e7f2a9d851'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hangar_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'location_id', 'type_id')
    )
    op.create_index(op.f('ix_hangar_stock_corporation_id'), 'hangar_stock', ['corporation_id'], unique=False)
    op.create_table('hangar_sync',
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('corporation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hangar_sync')
    op.drop_index(op.f('ix_hangar_stock_corporation_id'), table_name='hangar_stock')
    op.drop_table('hangar_stock')
    # ### end Alembic commands ###
