"""pricing rule folder

Revision ID: 413c217e6117
Revises: 92d2c4c309dc
Create Date: 2026-06-20 22:48:54.676896

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413c217e6117'
down_revision: str | None = '92d2c4c309dc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('folder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'folder')
    # ### end Alembic commands ###
