"""Add market price cache

Revision ID: 509cda97b1ab
Revises: a47995149b24
Create Date: 2026-06-07 09:26:10.167128

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509cda97b1ab'
down_revision: str | None = 'a47995149b24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('hub_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('buy_weighted_average', sa.Numeric(), nullable=False),
    sa.Column('buy_max', sa.Numeric(), nullable=False),
    sa.Column('buy_min', sa.Numeric(), nullable=False),
    sa.Column('buy_median', sa.Numeric(), nullable=False),
    sa.Column('buy_percentile', sa.Numeric(), nullable=False),
    sa.Column('buy_volume', sa.Numeric(), nullable=False),
    sa.Column('buy_order_count', sa.Integer(), nullable=False),
    sa.Column('sell_weighted_average', sa.Numeric(), nullable=False),
    sa.Column('sell_max', sa.Numeric(), nullable=False),
    sa.Column('sell_min', sa.Numeric(), nullable=False),
    sa.Column('sell_median', sa.Numeric(), nullable=False),
    sa.Column('sell_percentile', sa.Numeric(), nullable=False),
    sa.Column('sell_volume', sa.Numeric(), nullable=False),
    sa.Column('sell_order_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hub_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_prices')
    # ### end Alembic commands ###
