"""pricing rule compressed_only

Revision ID: 52b61153a13d
Revises: 14d2c0ed584b
Create Date: 2026-06-08 00:20:16.636695

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b61153a13d'
down_revision: str | None = '14d2c0ed584b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('compressed_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'compressed_only')
    # ### end Alembic commands ###
