"""reconciliation_events (ADR-0044 hangar sync log)

Revision ID: 54621089bc75
Revises: e36a851b0600
Create Date: 2026-07-14 00:04:49.793979

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54621089bc75'
down_revision: str | None = 'e36a851b0600'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('excess', 'shortfall', name='reconciliation_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=True),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_events_corporation_id'), 'reconciliation_events', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_events_corporation_id'), table_name='reconciliation_events')
    op.drop_table('reconciliation_events')
    # ### end Alembic commands ###
