"""buyback config default_accepted

Revision ID: 5639d755bd32
Revises: 07757f6adc0a
Create Date: 2026-06-08 00:38:47.572219

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5639d755bd32'
down_revision: str | None = '07757f6adc0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyback_configs', sa.Column('default_accepted', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyback_configs', 'default_accepted')
    # ### end Alembic commands ###
