"""receivables (ADR-0045 manual entries)

Revision ID: 7e4bdad3ab3e
Revises: c435cf22ca5d
Create Date: 2026-08-10 20:34:24.508430

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4bdad3ab3e'
down_revision: str | None = 'c435cf22ca5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_by_character_id', sa.BigInteger(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('cleared_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_corporation_id'), 'receivables', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_corporation_id'), table_name='receivables')
    op.drop_table('receivables')
    # ### end Alembic commands ###
