"""appraisal_contract_links

Revision ID: 92d2c4c309dc
Revises: f1a2c3d4e5b6
Create Date: 2026-06-19 00:16:54.218430

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d2c4c309dc'
down_revision: str | None = 'f1a2c3d4e5b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appraisal_id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_id'),
    sa.UniqueConstraint('corporation_id', 'contract_id', name='uq_appraisal_contract_corp_contract')
    )
    op.create_index(op.f('ix_appraisal_contracts_corporation_id'), 'appraisal_contracts', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appraisal_contracts_corporation_id'), table_name='appraisal_contracts')
    op.drop_table('appraisal_contracts')
    # ### end Alembic commands ###
