"""instance settings (runtime-editable access price, ADR-0042)

Revision ID: 9b06e114f03a
Revises: fb297d8946c8
Create Date: 2026-07-11 01:28:58.411594

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b06e114f03a'
down_revision: str | None = 'fb297d8946c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_settings')
    # ### end Alembic commands ###
