"""buyback_locations and appraisal delivery snapshot

Revision ID: a238fb904f45
Revises: b2f1a9c7e004
Create Date: 2026-06-09 23:19:22.103401

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a238fb904f45'
down_revision: str | None = 'b2f1a9c7e004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyback_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('npc_station', 'structure', name='location_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'location_id')
    )
    op.add_column('appraisals', sa.Column('delivery_location_id', sa.String(), nullable=True))
    op.add_column('appraisals', sa.Column('delivery_location_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appraisals', 'delivery_location_name')
    op.drop_column('appraisals', 'delivery_location_id')
    op.drop_table('buyback_locations')
    # ### end Alembic commands ###
