"""Add SDE reference data

Revision ID: a47995149b24
Revises: 10041312d2a3
Create Date: 2026-06-07 09:25:55.077513

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47995149b24'
down_revision: str | None = '10041312d2a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sde_market_groups',
    sa.Column('market_group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('market_group_id')
    )
    op.create_table('sde_metadata',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type_count', sa.Integer(), nullable=False),
    sa.Column('market_group_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sde_types',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    with op.batch_alter_table('sde_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sde_types_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sde_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sde_types_name'))

    op.drop_table('sde_types')
    op.drop_table('sde_metadata')
    op.drop_table('sde_market_groups')
    # ### end Alembic commands ###
