"""Add pricing config, rules, appraisals

Revision ID: a668a2fb711c
Revises: 509cda97b1ab
Create Date: 2026-06-07 10:25:59.179006

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a668a2fb711c'
down_revision: str | None = '509cda97b1ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('created_by_character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('market_hub_id', sa.Integer(), nullable=False),
    sa.Column('accepted_total', sa.Numeric(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.corporation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appraisals_public_id'), ['public_id'], unique=True)

    op.create_table('buyback_configs',
    sa.Column('corporation_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('market_hub_id', sa.Integer(), nullable=False),
    sa.Column('default_basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('default_percentage', sa.Numeric(), nullable=False),
    sa.Column('aggregate_field', sa.Enum('weighted_average', 'max', 'min', 'median', 'percentile', name='aggregate_field', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.corporation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('corporation_id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.Enum('market_group', 'type', name='target_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.corporation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'target_kind', 'target_id', name='uq_pricing_rule_target')
    )
    op.create_table('appraisal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', name='line_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=True),
    sa.Column('unit_value', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appraisal_lines')
    op.drop_table('pricing_rules')
    op.drop_table('buyback_configs')
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appraisals_public_id'))

    op.drop_table('appraisals')
    # ### end Alembic commands ###
