"""initial postgres schema

Revision ID: a6cb1eb62c7c
Revises: 
Create Date: 2026-06-07 19:20:49.177147

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cb1eb62c7c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eve_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eve_id')
    )
    op.create_table('corporations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eve_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ceo_character_id', sa.Integer(), nullable=False),
    sa.Column('registered_by_character_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eve_id')
    )
    op.create_table('market_prices',
    sa.Column('hub_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('buy_weighted_average', sa.Numeric(), nullable=False),
    sa.Column('buy_max', sa.Numeric(), nullable=False),
    sa.Column('buy_min', sa.Numeric(), nullable=False),
    sa.Column('buy_median', sa.Numeric(), nullable=False),
    sa.Column('buy_percentile', sa.Numeric(), nullable=False),
    sa.Column('buy_volume', sa.Numeric(), nullable=False),
    sa.Column('buy_order_count', sa.Integer(), nullable=False),
    sa.Column('sell_weighted_average', sa.Numeric(), nullable=False),
    sa.Column('sell_max', sa.Numeric(), nullable=False),
    sa.Column('sell_min', sa.Numeric(), nullable=False),
    sa.Column('sell_median', sa.Numeric(), nullable=False),
    sa.Column('sell_percentile', sa.Numeric(), nullable=False),
    sa.Column('sell_volume', sa.Numeric(), nullable=False),
    sa.Column('sell_order_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hub_id', 'type_id')
    )
    op.create_table('sde_market_groups',
    sa.Column('market_group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('market_group_id')
    )
    op.create_table('sde_metadata',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type_count', sa.Integer(), nullable=False),
    sa.Column('market_group_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sde_types',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sde_types_name'), 'sde_types', ['name'], unique=False)
    op.create_table('appraisals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market_hub_id', sa.Integer(), nullable=False),
    sa.Column('accepted_total', sa.Numeric(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisals_public_id'), 'appraisals', ['public_id'], unique=True)
    op.create_table('buyback_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('market_hub_id', sa.Integer(), nullable=False),
    sa.Column('default_basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('default_percentage', sa.Numeric(), nullable=False),
    sa.Column('aggregate_field', sa.Enum('weighted_average', 'max', 'min', 'median', 'percentile', name='aggregate_field', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id')
    )
    op.create_table('manager_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_character_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'character_id', name='uq_manager_corp_char')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.Enum('market_group', 'type', name='target_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'target_kind', 'target_id', name='uq_pricing_rule_target')
    )
    op.create_table('appraisal_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appraisal_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', name='line_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('basis', sa.Enum('buy', 'sell', 'split', name='basis', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('percentage', sa.Numeric(), nullable=True),
    sa.Column('unit_value', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('line_total', sa.Numeric(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appraisal_lines')
    op.drop_table('pricing_rules')
    op.drop_table('manager_assignments')
    op.drop_table('buyback_configs')
    op.drop_index(op.f('ix_appraisals_public_id'), table_name='appraisals')
    op.drop_table('appraisals')
    op.drop_index(op.f('ix_sde_types_name'), table_name='sde_types')
    op.drop_table('sde_types')
    op.drop_table('sde_metadata')
    op.drop_table('sde_market_groups')
    op.drop_table('market_prices')
    op.drop_table('corporations')
    op.drop_table('characters')
    # ### end Alembic commands ###
