"""entitlements table (ADR-0042, paid accounting add-on)

One row per (corp, feature): a corp's access to a paid add-on, granted by an app admin
(ADR-0041) or extended by matched ISK payment. NULL expires_at = perpetual grant.

Revision ID: ab4b575e19cd
Revises: 413c217e6117
Create Date: 2026-07-09 20:59:29.835942

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4b575e19cd'
down_revision: str | None = '413c217e6117'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sa.Enum('accounting', name='feature', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('payment', 'admin', name='entitlement_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by_character_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'feature', name='uq_entitlement_corp_feature')
    )
    op.create_index(op.f('ix_entitlements_corporation_id'), 'entitlements', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitlements_corporation_id'), table_name='entitlements')
    op.drop_table('entitlements')
    # ### end Alembic commands ###
