"""buyback_config hub source fields

Revision ID: b78a43a8d166
Revises: 5639d755bd32
Create Date: 2026-06-09 14:56:40.696643

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78a43a8d166'
down_revision: str | None = '5639d755bd32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyback_configs', sa.Column('market_hub_kind', sa.Enum('npc_station', 'structure', name='market_hub_kind', native_enum=False, create_constraint=True), server_default=sa.text("'npc_station'"), nullable=False))
    op.add_column('buyback_configs', sa.Column('market_region_id', sa.Integer(), nullable=True))
    op.add_column('buyback_configs', sa.Column('market_hub_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyback_configs', 'market_hub_name')
    op.drop_column('buyback_configs', 'market_region_id')
    op.drop_column('buyback_configs', 'market_hub_kind')
    # ### end Alembic commands ###
