"""sales ingestion: wallet division, corp_market_orders, new log kinds

Revision ID: c435cf22ca5d
Revises: 81914dc0785e
Create Date: 2026-08-10 18:37:10.553716

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c435cf22ca5d'
down_revision: str | None = '81914dc0785e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corp_market_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('is_buy_order', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('volume_remain', sa.BigInteger(), nullable=False),
    sa.Column('volume_total', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('wallet_division', sa.Integer(), nullable=False),
    sa.Column('issued', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'order_id')
    )
    op.create_index(op.f('ix_corp_market_orders_corporation_id'), 'corp_market_orders', ['corporation_id'], unique=False)
    op.add_column('buyback_configs', sa.Column('wallet_division', sa.Integer(), nullable=True))
    # New log kinds (ADR-0045): widen the ADR-0021 VARCHAR (longest value is now 19
    # chars) AND recreate the CHECK — an alter_column alone leaves the old check
    # behind (the #177 lesson, caught by the migration-built e2e database).
    op.drop_constraint('reconciliation_kind', 'reconciliation_events', type_='check')
    op.alter_column('reconciliation_events', 'kind',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=19),
               existing_nullable=False)
    op.create_check_constraint(
        'reconciliation_kind',
        'reconciliation_events',
        "kind IN ('excess', 'shortfall', 'reprocess_hint', 'unmatched_sale', "
        "'unexpected_division')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fails if unmatched_sale / unexpected_division rows exist — delete them first.
    op.drop_constraint('reconciliation_kind', 'reconciliation_events', type_='check')
    op.alter_column('reconciliation_events', 'kind',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.create_check_constraint(
        'reconciliation_kind',
        'reconciliation_events',
        "kind IN ('excess', 'shortfall', 'reprocess_hint')",
    )
    op.drop_column('buyback_configs', 'wallet_division')
    op.drop_index(op.f('ix_corp_market_orders_corporation_id'), table_name='corp_market_orders')
    op.drop_table('corp_market_orders')
    # ### end Alembic commands ###
