"""buyback_hangars (ADR-0044 hangar config)

Revision ID: e36a851b0600
Revises: 16685d146ad7
Create Date: 2026-07-12 21:19:33.395319

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36a851b0600'
down_revision: str | None = '16685d146ad7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyback_hangars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('division BETWEEN 1 AND 7', name='hangar_division_range'),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_id', 'location_id', 'division')
    )
    op.create_index(op.f('ix_buyback_hangars_corporation_id'), 'buyback_hangars', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyback_hangars_corporation_id'), table_name='buyback_hangars')
    op.drop_table('buyback_hangars')
    # ### end Alembic commands ###
