"""lot ledger: lots, transformations, sales, expenses (ADR-0043/0047)

The accounting core: lots (one acquisition of one type at one cost basis, consumed
FIFO), the ADR-0047 transformation hook (source_lot_id self-FK + the event table),
sales (one row per lot touched — the only place revenue is recorded), and expenses
(selling costs, attributed to lots where identifiable). Money is Numeric (ADR-0020);
quantities are BigInteger (EVE hauls exceed 2^31).

Revision ID: f07d87092084
Revises: 9b06e114f03a
Create Date: 2026-07-12 09:39:48.339724

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07d87092084'
down_revision: str | None = '9b06e114f03a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('qty_original', sa.BigInteger(), nullable=False),
    sa.Column('qty_remaining', sa.BigInteger(), nullable=False),
    sa.Column('unit_purchase_cost', sa.Numeric(), nullable=False),
    sa.Column('unit_hauling_cost', sa.Numeric(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('buyback', 'opening_balance', 'manual', 'reprocess', name='lot_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('appraisal_id', sa.Uuid(), nullable=True),
    sa.Column('source_lot_id', sa.Uuid(), nullable=True),
    sa.Column('cost_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('written_down_to', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lots_corp_type', 'lots', ['corporation_id', 'item_type_id'], unique=False)
    op.create_index(op.f('ix_lots_corporation_id'), 'lots', ['corporation_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('broker_fee', 'relist_fee', 'hauling', 'write_down', 'other', name='expense_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('esi', 'manual', name='entry_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_ref', sa.BigInteger(), nullable=True),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    op.create_index(op.f('ix_expenses_corporation_id'), 'expenses', ['corporation_id'], unique=False)
    op.create_table('lot_transformations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('source_lot_id', sa.Uuid(), nullable=False),
    sa.Column('qty_consumed', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_transformations_corporation_id'), 'lot_transformations', ['corporation_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('unit_proceeds', sa.Numeric(), nullable=False),
    sa.Column('sales_tax', sa.Numeric(), nullable=False),
    sa.Column('channel', sa.Enum('market', 'contract', 'direct', name='sale_channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('esi', 'manual', name='entry_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_ref', sa.BigInteger(), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_ref', 'lot_id', name='uq_sale_channel_ref_lot')
    )
    op.create_index(op.f('ix_sales_corporation_id'), 'sales', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_corporation_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_lot_transformations_corporation_id'), table_name='lot_transformations')
    op.drop_table('lot_transformations')
    op.drop_index(op.f('ix_expenses_corporation_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_lots_corporation_id'), table_name='lots')
    op.drop_index('ix_lots_corp_type', table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
