"""move suggestions (ADR-0049 move detection)

Revision ID: f7eedcc96e85
Revises: c9a41b7d20ef
Create Date: 2026-08-11 14:56:38.440396

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7eedcc96e85'
down_revision: str | None = 'c9a41b7d20ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corporation_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('origin_location_id', sa.String(), nullable=False),
    sa.Column('destination_location_id', sa.String(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('shortfall_event_id', sa.Uuid(), nullable=False),
    sa.Column('excess_lot_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'dismissed', name='move_suggestion_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excess_lot_id'], ['lots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shortfall_event_id'], ['reconciliation_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_move_suggestions_corporation_id'), 'move_suggestions', ['corporation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_suggestions_corporation_id'), table_name='move_suggestions')
    op.drop_table('move_suggestions')
    # ### end Alembic commands ###
