"""operator wallet token + wallet payments (ADR-0042)

The instance operator's encrypted wallet credential (singleton; reads their own wallet
journal for payment reconciliation) and the audit trail of incoming ISK transfers,
keyed by EVE journal id so re-polling never records a payment twice.

Revision ID: fb297d8946c8
Revises: ab4b575e19cd
Create Date: 2026-07-10 20:15:24.201333

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb297d8946c8'
down_revision: str | None = 'ab4b575e19cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_wallet_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_eve_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_refresh_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('sender_eve_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matched_corporation_id', sa.Uuid(), nullable=True),
    sa.Column('periods_granted', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_by_character_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['matched_corporation_id'], ['corporations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_payments')
    op.drop_table('operator_wallet_tokens')
    # ### end Alembic commands ###
